- apps/picsa-apps/extension-app-native/.gitignore
- apps/picsa-apps/extension-app-native/android/app/capacitor.build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.config.json
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.plugins.json
- apps/picsa-apps/extension-app-native/android/capacitor.settings.gradle
- apps/picsa-apps/extension-app-native/capacitor.config.ts
- apps/picsa-tools/resources-tool/src/app/stores/resources.store.ts
- libs/shared/src/services/native/storage-service.ts
- package.json
- yarn.lock
Minor updates to fix how files are copied from assets and written to local file system
> fix: add blob write and prevent res caching

- .gitignore
- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/resources-tool/src/app/data/workshops/mw-salima-2022.ts
- apps/picsa-tools/resources-tool/src/assets/resources/contents.json
- package.json
> chore: update resources

- apps/picsa-apps/extension-app-native/android/app/capacitor.build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.config.json
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.plugins.json
- apps/picsa-apps/extension-app-native/android/capacitor.settings.gradle
- apps/picsa-apps/extension-app-native/capacitor.config.ts
> chore: code tidying

- apps/picsa-apps/extension-app-native/android/app/capacitor.build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.config.json
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.plugins.json
- apps/picsa-apps/extension-app-native/android/capacitor.settings.gradle
- apps/picsa-apps/extension-app-native/capacitor.config.ts
- apps/picsa-apps/extension-app/src/app/app.component.ts
- libs/shared/src/services/core/performance.service.ts
- package.json
- yarn.lock
Add performance monitoring support
**Example dashboard showing startup delay (from testing version)**
> feat: add support for firebase perf monitoring

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/AndroidManifest.xml
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.config.json
- apps/picsa-apps/extension-app/src/static/.well-known/assetlinks.json
- package.json
> chore: update deep link config

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/resources-tool/src/app/components/resource-item/resource-item.component.scss
- package.json
Fix issue where resources overflow on small screens
> fix: resource style for small screens

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-apps/extension-app/project.json
- apps/picsa-tools/resources-tool/src/assets/resources/contents.json
- package.json
Add sourcemap support for help in debugging
> chore: update sourcemaps

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Add support for automated release-notes drafter
> ci: add release drafter

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- libs/environments/src/version.ts
- package.json
> chore: update version 3.15.0

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/budget-tool/src/app/components/import-dialog/import-dialog.component.scss
- libs/environments/src/version.ts
- libs/shared/src/services/core/db/_server.db.ts
- libs/theme/src/_overrides.scss
- package.json
Fix budget import regression bug introduced with recent core dependency updates
> fix: budget import

- apps/picsa-apps/extension-app-native/android/.idea/compiler.xml
- apps/picsa-apps/extension-app-native/android/.idea/misc.xml
- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.plugins.json
- apps/picsa-apps/extension-app-native/android/build.gradle
- apps/picsa-apps/extension-app-native/android/gradle/wrapper/gradle-wrapper.properties
- apps/picsa-tools/budget-tool/src/app/pages/view/budget-view.page.ts
- libs/components/src/components/back-button.component.ts
- libs/components/src/components/picsa-header.component.ts
- libs/components/src/services/components.service.ts
- libs/environments/src/version.ts
- package.json
Fix issue where next button in budget tool would not work alongside back button
> fix(budget): android back button implementation

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- package.json
- Update translations from latest provided by translators
- Add support for _Chinyanja_ language variation for Zambia
_Note_ - the updated translations were already accidentally comitted to main branch in a974606b623f61172f86dd980c907b6811a87ea4 so this PR just to keep record in changelog
> Feat(translations) Update latest translations

- apps/picsa-tools/resources-tool/src/app/data/picsa/cropInfo.ts
> fix(resources): kasungu crop info sheet

- apps/picsa-apps/extension-app-native/android/.idea/misc.xml
- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/assets/capacitor.config.json
- apps/picsa-apps/extension-app-native/capacitor.config.ts
- apps/picsa-tools/manual-tool/project.json
- apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.html
- apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.scss
- apps/picsa-tools/manual-tool/src/app/components/pdf-viewer/pdf-viewer.component.ts
- apps/picsa-tools/monitoring-tool/src/app/pages/form/form-view/form-view.component.ts
- libs/environments/src/version.ts
- libs/i18n/assets/mw_ny.json
- libs/i18n/assets/zm_ny.json
- libs/i18n/source/mw_ny.json
- libs/i18n/source/zm_ny.json
- libs/shared/src/services/native/storage-service.ts
- package.json
Fix bug where some resources fail to download
Remove zoom in/out buttons on mobile pdf viewer (pinch zoom works better)
Improve paging buttons on mobile layout
> Hotfix(manual) - caching and pdf viewer layout

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- libs/environments/src/version.ts
- package.json
- yarn.lock
Minor capacitor update that fixes issue seen on some android 8 and huawei devices
`https://github.com/ionic-team/capacitor/issues/6911`
**[Crash report](https://console.firebase.google.com/u/0/project/picsa-apps/crashlytics/app/android:io.picsa.extension/issues/eb527fcb2d82427b98063592da75ca41?time=last-seven-days)**
> chore: bump capacitor version

- .github/workflows/android-release.yml
- apps/picsa-apps/extension-app-native/android/app/build.gradle
- package.json
- yarn.lock
Attempt to pin capacitor version more directly as issue supposedly fixed by #180 still appearing (may otherwise be incomplete fix by capacitor)
> chore: pin capacitor core version

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- libs/environments/src/version.ts
- package.json
- yarn.lock
Additional change to fix issue identified in #180
> chore: bump capacitor-android version

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/resources-tool/src/app/components/resource-download/resource-download.component.html
- libs/environments/src/version.ts
- package.json
Fix resource download progress
> fix: resource download progress

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/resources-tool/src/app/data/weather/links.ts
- libs/environments/src/version.ts
- package.json
Fix issue where dccms daily forecast link not showing
> content: fix mw dccms link

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/farmer-activity/src/app/pages/activity-details/activity-details.component.ts
- apps/picsa-tools/resources-tool/src/app/data/picsa/farmer-videos.ts
- libs/environments/src/version.ts
- package.json
- Add farmer videos for Zambia Nyanja
> Content: Farmer Videos ZM

- libs/shared/src/services/core/db_v2/db-sync.service.ts
Fix issue where UI would report successful monitoring form sync as unsuccessful
> fix: supabase db sync code

- .github/release-drafter.yml
- .github/workflows/gh-release-drafter.yml
> Refactor: release drafter template

- .github/pr-labeler.config.yml
- .github/workflows/gh-pr-label-paths.yml
- .github/workflows/gh-pr-label-title.yml
Upgrade ci pr labeller action major version, config changes and action target update
> chore: update action target

- apps/picsa-tools/farmer-activity/src/app/pages/activity-details/activity-details.component.html
Fix bug where farmer-activity videos fail to play on web (duplicate video players on page)
> fix: video player web

- apps/picsa-apps/dashboard/src/app/modules/monitoring/monitoring-forms.module.ts
- apps/picsa-apps/dashboard/src/app/modules/monitoring/monitoring.service.ts
- apps/picsa-apps/dashboard/src/app/modules/monitoring/pages/home/monitoring.page.html
- apps/picsa-apps/dashboard/src/app/modules/monitoring/pages/home/monitoring.page.ts
- apps/picsa-apps/dashboard/src/app/modules/monitoring/pages/update/update-monitoring-forms.component.html
- apps/picsa-apps/dashboard/src/app/modules/monitoring/pages/update/update-monitoring-forms.component.scss
- apps/picsa-apps/dashboard/src/app/modules/monitoring/pages/update/update-monitoring-forms.component.ts
- libs/shared/src/services/core/notification.service.ts
- libs/shared/src/services/core/supabase/components/upload/supabase-upload.component.ts
- package.json
- yarn.lock
This PR adds a page that enables creation and updating of forms. It also enables the user to update multiple fields and the cover image
Following the issue #256
Updated demo 2024-05-03
[Screenity video - May 3, 2024.webm](https://github.com/e-picsa/picsa-apps/assets/10515065/b25bd3b6-a230-434c-93ff-8e65a5a41818)
---
> feat(dashboard): new form create and edit

- apps/picsa-apps/dashboard/src/index.html
- libs/theme/src/themes/_index.scss
- libs/theme/src/themes/picsa-dashboard.scss
Update dashboard theme to use inversion of new farmer app theme. This makes it easier to identify which app is in use
> chore: update dashboard theme

- apps/picsa-apps/dashboard/src/app/modules/climate/pages/station-details/components/rainfall-summary/rainfall-summary.html
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/station-details/components/rainfall-summary/rainfall-summary.ts
Update dashboard to refresh rainfall summaries
> fix: rainfall summary refresh

- apps/picsa-apps/dashboard/src/app/app.config.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/climate-api.mapping.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/climate.service.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/components/api-status/api-status.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/forecast/forecast.component.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/station-details/components/rainfall-summary/rainfall-summary.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/station/station.component.html
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/station/station.component.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/types/api.d.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/types/db.d.ts
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/variety-details/variety-details.component.ts
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/variety/variety.component.ts
- apps/picsa-apps/dashboard/src/app/modules/error-handler.ts
- apps/picsa-apps/dashboard/src/app/modules/monitoring/monitoring.service.ts
- apps/picsa-apps/dashboard/src/app/modules/profile/components/sign-in-dialog/sign-in-dialog.component.ts
- apps/picsa-apps/dashboard/src/app/modules/resources/pages/files/edit/resource-file-edit.component.ts
- apps/picsa-apps/dashboard/src/app/modules/resources/resources.service.ts
- libs/shared/src/services/core/notification.service.ts
- libs/shared/src/services/core/supabase/components/upload/supabase-upload.component.ts
- libs/shared/src/services/core/supabase/services/supabase-storage.service.ts
Update dashboard climate pages to fix breaking changes from recent API updates
> chore: dashboard api updates

- libs/shared/src/features/photo/components/photo-view/photo-view.component.html
- libs/shared/src/features/photo/components/photo-view/photo-view.component.scss
- libs/shared/src/features/photo/components/photo-view/photo-view.component.ts
- Implemented a mat dialog to display a larger view of selected images.
- Close and delete buttons were added to the dialog for better user interaction.
- Improved mobile responsiveness of the photo view component.
- Resolves #305.
**Latest**
[Screenity video - Jul 31, 2024.webm](https://github.com/user-attachments/assets/b24f4070-fb61-4ebf-a8d6-724605173dde)
---
https://github.com/user-attachments/assets/7f712d87-ce43-40e3-b2bd-a9d644b30ac7
> feat: Add photo dialog viewer to photo view component

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-apps/extension-app-native/android/app/src/main/AndroidManifest.xml
- libs/environments/src/version.ts
- package.json
Fix issue where android devices were not requesting geolocaiton permission for climate tool automated site select
> fix: geolocation permission

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- libs/data/resources/videos/testimonials.ts
- libs/environments/src/version.ts
- package.json
- Swap testimonial videos for zambia and malawi
> chore: update testimonial videos

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-apps/extension-app/src/app/components/layout.html
- package.json
- Add forecasts button to menu (commit not pushed to previous pr)
> fix: forecasts menu item

- apps/picsa-apps/extension-app-native/android/.idea/misc.xml
- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/option-tool/src/app/components/editor/editor.component.html
- apps/picsa-tools/option-tool/src/app/components/editor/editor.component.scss
- apps/picsa-tools/option-tool/src/app/pages/home/home.component.html
- apps/picsa-tools/option-tool/src/app/pages/home/home.component.scss
- libs/environments/src/version.ts
- libs/theme/src/_overrides.scss
- package.json
Various improvements to options tool layout on smaller devices
**Options table display more compact for viewing on mobile**
**Options editor popup sizing improved, with support for scrolling longer sections**
> style: improve option tool responsiveness

- apps/picsa-apps/extension-app/src/app/app.component.ts
- libs/shared/src/services/core/performance.service.ts
- libs/shared/src/services/core/push-notifications.service.ts
Fix issue where native-only services fail to initialise on web
> fix: push notification and performance service init

- .vscode/settings.json
- apps/picsa-apps/extension-app/src/app/app.component.ts
- apps/picsa-apps/extension-app/src/app/components/layout.html
- apps/picsa-apps/extension-app/src/app/components/layout.ts
- apps/picsa-apps/extension-app/src/app/pages/home/home.page.ts
- apps/picsa-server/scripts/crop-probability-parser/src/data/districts.ts
- apps/picsa-tools/budget-tool/src/app/store/budget.store.ts
- apps/picsa-tools/budget-tool/src/app/store/templates.ts
- apps/picsa-tools/climate-tool/src/app/pages/site-view/site-view.page.ts
- apps/picsa-tools/crop-probability-tool/src/app/components/station-select/station-select.component.ts
- apps/picsa-tools/extension-content/src/app/pages/home/extension-home.component.html
- apps/picsa-tools/extension-content/src/app/pages/home/extension-home.component.ts
- apps/picsa-tools/farmer-content/src/app/pages/module-home/module-home.component.ts
- apps/picsa-tools/resources-tool/src/app/services/resources-tool.service.ts
- libs/environments/src/version.ts
- libs/migrations/migrations.service.ts
- libs/shared/src/features/photo/components/photo-view/photo-view.component.ts
- libs/shared/src/services/core/analytics.service.ts
- fix service init issue
- replace references to app_version number with semver
- remove legacy signal permissions
> Chore: core tidying

- .eslintrc.json
- apps/picsa-tools/budget-tool/src/app/components/budget-tool.components.ts
- apps/picsa-tools/budget-tool/src/app/data/cards.ts
- libs/shared/src/modules/translate/translate.module.ts
Fix issue where duplicate ids for input and output cards would cause error when running locally
> fix: budget tool cards

- apps/picsa-apps/extension-app-native/android/app/build.gradle
- apps/picsa-tools/farmer-content/src/app/app.component.ts
- apps/picsa-tools/farmer-content/src/app/pages/module-home/module-home.component.ts
- apps/picsa-tools/farmer-content/src/app/services/farmer-content.service.ts
- libs/environments/src/version.ts
- libs/forms/forms.module.ts
- package.json
> fix: farmer-tool-header

- libs/shared/src/features/video-player/player/video-player.web.ts
Fix issue where portrait videos scaled incorrectly on web
> fix: web portrait videos

- apps/picsa-apps/dashboard/src/app/app.component.ts
- apps/picsa-apps/dashboard/src/app/data/index.ts
- libs/data/climate/chart_definitions/default.ts
> Chore(dashboard): version update

- apps/picsa-server/supabase/data/climate_stations_rows.csv
- Add more stations to seed data to allow linked downscaled data to populate correctly db seed
> fix: dev seed data

- apps/picsa-server/supabase/migrations/20250706100000_forecast_cleanup_cron.sql
> hotfix: update db forecast_type enum

- .github/workflows/android-release.yml
- apps/picsa-tools/monitoring-tool/src/app/models/strings.ts
- libs/i18n/assets/debug.json
- libs/i18n/assets/global_en.json
- libs/i18n/assets/ke_sw.json
- libs/i18n/assets/mw_ny.json
- libs/i18n/assets/tj_tg.json
- libs/i18n/assets/zm_ny.json
- libs/i18n/templates/_template.csv
- libs/i18n/templates/_template.json
- Fix android release to target Java 21
- Update latest translations
> Fix: android release workflow

- apps/picsa-apps/app-native/android/app/build.gradle
- apps/picsa-apps/app-native/android/app/capacitor.build.gradle
- apps/picsa-apps/app-native/android/app/src/main/res/drawable/picsa_splash_static.xml
- apps/picsa-apps/app-native/android/app/src/main/res/values-v31/styles.xml
- apps/picsa-apps/app-native/android/app/src/main/res/values-v35/styles.xml
- apps/picsa-apps/app-native/android/app/src/main/res/values/styles.xml
- apps/picsa-apps/app-native/android/app/src/main/res/values/themes.xml
- apps/picsa-apps/app-native/android/capacitor.settings.gradle
- apps/picsa-apps/app-native/capacitor.config.ts
- apps/picsa-apps/app/src/index.html
- libs/configuration/src/provider.ts
- libs/environments/src/version.ts
- package.json
- yarn.lock
- Fix android 15 handling of edge-to-edge styles
- Fix legacy splash screen handling
> Chore: android style updates

- apps/picsa-apps/dashboard/src/app/modules/translations/pages/import/components/xlsx-import/xlsx-import.component.html
- apps/picsa-apps/dashboard/src/app/modules/translations/pages/import/components/xlsx-import/xlsx-import.component.ts
- libs/utils/xlsx.ts
Add XLSX translation list export
> feat: xlsx template export

- apps/picsa-tools/resources-tool/src/app/components/resource-download/resource-download.component.html
> fix: download progress spinner

- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/probability/downscaled/components/probability-table/probability-table.component.html
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/probability/downscaled/components/probability-table/probability-table.component.scss
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/probability/downscaled/components/probability-table/probability-table.component.ts
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/probability/downscaled/probability-downscaled.component.html
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/probability/downscaled/probability-downscaled.component.ts
- apps/picsa-apps/dashboard/src/app/modules/crop-information/pages/probability/probability.component.ts
- apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.html
- apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.scss
- apps/picsa-tools/crop-probability-tool/src/app/components/crop-probability-table/crop-probability-table.component.ts
- Add start of season probabilities to dashboard crop probabilities
- Improve table styling for word export
**Crop Probability Table** - Includes season start probabilities and formatted better for printing
> Feat(dashboard): climate season start probabilities

- libs/shared/src/services/core/network.service.ts
> feat: online status detect

- libs/shared/src/services/appUser.service.ts
- libs/shared/src/services/core/network.service.ts
- libs/utils/angular.ts
> refactor: app user data sync

- .github/workflows/android-release.yml
- .github/workflows/web-release-dashboard.yml
- .github/workflows/web-release.yml
- apps/picsa-apps/app-native/android/app/build.gradle
- apps/picsa-server/scripts/db-seed/db-seed.ts
- libs/environments/src/environment.prod.ts
- libs/environments/src/environment.ts
- libs/environments/src/supabase/config.example.json
- libs/environments/src/version.ts
- libs/models/src/models.ts
- libs/shared/src/services/core/supabase/services/supabase-auth.service.ts
- package.json
> Fix: app user native

- apps/picsa-apps/app-native/android/app/build.gradle
- apps/picsa-apps/app/src/app/app.component.ts
- package.json
Fix issue where service init order would block some functionality
> Fix: app init order

- apps/picsa-apps/dashboard/src/app/modules/climate/climate.service.ts
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/admin/admin.component.html
- apps/picsa-apps/dashboard/src/app/modules/climate/pages/admin/admin.component.ts
- apps/picsa-server/supabase/migrations/20250906184901_audit_functions.sql
- apps/picsa-server/supabase/migrations/20250906184902_audit_utils.sql
- apps/picsa-server/supabase/migrations/20250906190000_climate_data_audit.sql
- Add better visual for partially complete updates
- Change api requests to trigger sequentially instead of concurrently (limit server usage, reduce server errors)
> Feat(dashboard): climate data admin ui improvements

- apps/picsa-scripts/src/media/process.ts
- libs/data/resources/videos/digitalSkills.ts
- libs/data/resources/videos/intro.ts
> content: video updates
